export enum GET_LEADERBOARD {
  REQUEST = 'GET_LEADERBOARD_REQUEST',
  SUCCESS = 'GET_LEADERBOARD_SUCCESS',
  FAILURE = 'GET_LEADERBOARD_FAILURE',
}

export enum ADD_LEADERBOARD {
  REQUEST = 'ADD_LEADERBOARD_REQUEST',
  SUCCESS = 'ADD_LEADERBOARD_SUCCESS',
  FAILURE = 'ADD_LEADERBOARD_FAILURE',
  SET_SHOW_MODAL = 'ADD_LEADERBOARD_SET_SHOW_MODAL',
}

export enum REMOVE_LEADERBOARD {
  REQUEST = 'REMOVE_LEADERBOARD_REQUEST',
  SUCCESS = 'REMOVE_LEADERBOARD_SUCCESS',
  FAILURE = 'REMOVE_LEADERBOARD_FAILURE',
  SET_SELECTED_ID = 'REMOVE_LEADERBOARD_SET_SELECTED_ID',
}
