export enum GET_LEADERBOARD {
  REQUEST = 'GET_LEADERBOARD_REQUEST',
  SUCCESS = 'GET_LEADERBOARD_SUCCESS',
  FAILURE = 'GET_LEADERBOARD_FAILURE',
}

export enum ADD_LEADERBOARD {
  REQUEST = 'ADD_LEADERBOARD_REQUEST',
  SUCCESS = 'ADD_LEADERBOARD_SUCCESS',
  FAILURE = 'ADD_LEADERBOARD_FAILURE',
  SET_SHOW_MODAL = 'ADD_LEADERBOARD_SET_SHOW_MODAL',
}
