export enum GET_TEAM {
  REQUEST = 'GET_TEAM_REQUEST',
  SUCCESS = 'GET_TEAM_SUCCESS',
  FAILURE = 'GET_TEAM_FAILURE',
  SET_PAGINATION = 'GET_TEAM_SET_PAGINATION',
  SET_TOURNAMENT_ID = 'GET_TEAM_SET_TOURNAMENT_ID',
}
